apiVersion: cloudguard.oci.upbound.io/v1alpha1
kind: BridgeEnvironment
metadata:
  annotations:
    meta.upbound.io/example-id: cloudguard/v1alpha1/bridgeenvironment
  labels:
    testing.upbound.io/example-name: test_environment
  name: test-environment
spec:
  forProvider:
    compartmentId: ${var.compartment_id}
    definedTags:
      Operations.CostCenter: "42"
    displayName: ${var.environment_display_name}
    freeformTags:
      Department: Finance
