apiVersion: cloudguard.oci.upbound.io/v1alpha1
kind: GuardCloudGuardConfiguration
metadata:
  annotations:
    meta.upbound.io/example-id: cloudguard/v1alpha1/guardcloudguardconfiguration
  labels:
    testing.upbound.io/example-name: test_cloud_guard_configuration
  name: test-cloud-guard-configuration
spec:
  forProvider:
    compartmentId: ${var.compartment_id}
    reportingRegion: ${var.cloud_guard_configuration_reporting_region}
    selfManageResources: ${var.cloud_guard_configuration_self_manage_resources}
    service_configurations:
    - service_configuration_type: ${var.cloud_guard_configuration_service_configurations_service_configuration_type}
      status: ${var.cloud_guard_configuration_service_configurations_status}
    status: ${var.cloud_guard_configuration_status}
