apiVersion: database.oci.upbound.io/v1alpha1
kind: ApplicationVip
metadata:
  annotations:
    meta.upbound.io/example-id: database/v1alpha1/applicationvip
  labels:
    testing.upbound.io/example-name: test_application_vip
  name: test-application-vip
spec:
  forProvider:
    cloudVmClusterId: ${oci_database_cloud_vm_cluster.test_cloud_vm_cluster.id}
    dbNodeId: ${oci_database_db_node.test_db_node.id}
    hostnameLabel: ${var.application_vip_hostname_label}
    ipAddress: ${var.application_vip_ip_address}
    ipv6address: ${var.application_vip_ipv6address}
    subnetId: ${oci_core_subnet.test_subnet.id}
