apiVersion: networking.oci.upbound.io/v1alpha1
kind: FirewallNetworkFirewallPolicyApplicationGroup
metadata:
  annotations:
    meta.upbound.io/example-id: networking/v1alpha1/firewallnetworkfirewallpolicyapplicationgroup
  labels:
    testing.upbound.io/example-name: test_network_firewall_policy_application_group
  name: test-network-firewall-policy-application-group
spec:
  forProvider:
    apps: ${var.network_firewall_policy_application_group_apps}
    networkFirewallPolicyId: ${oci_network_firewall_network_firewall_policy.test_network_firewall_policy.id}
