apiVersion: stackmonitoring.oci.upbound.io/v1alpha1
kind: MonitoringConfig
metadata:
  annotations:
    meta.upbound.io/example-id: stackmonitoring/v1alpha1/monitoringconfig
  labels:
    testing.upbound.io/example-name: test_config
  name: test-config
spec:
  forProvider:
    compartmentId: ${var.compartment_id}
    configType: ${var.config_config_type}
    definedTags:
      foo-namespace.bar-key: value
    displayName: ${var.config_display_name}
    freeformTags:
      bar-key: value
    isEnabled: ${var.config_is_enabled}
    license: ${var.config_license}
    resourceType: ${var.config_resource_type}
