apiVersion: devops.oci.upbound.io/v1alpha1
kind: BuildPipeline
metadata:
  annotations:
    meta.upbound.io/example-id: devops/v1alpha1/buildpipeline
  labels:
    testing.upbound.io/example-name: test_build_pipeline
  name: test-build-pipeline
spec:
  forProvider:
    buildPipelineParameters:
    - items:
      - defaultValue: ${var.build_pipeline_build_pipeline_parameters_items_default_value}
        description: ${var.build_pipeline_build_pipeline_parameters_items_description}
        name: ${var.build_pipeline_build_pipeline_parameters_items_name}
    definedTags:
      foo-namespace.bar-key: value
    description: ${var.build_pipeline_description}
    displayName: ${var.build_pipeline_display_name}
    freeformTags:
      bar-key: value
    projectId: ${oci_devops_project.test_project.id}
