apiVersion: devops.oci.upbound.io/v1alpha1
kind: RepositoryMirror
metadata:
  annotations:
    meta.upbound.io/example-id: devops/v1alpha1/repositorymirror
  labels:
    testing.upbound.io/example-name: test_repository_mirror
  name: test-repository-mirror
spec:
  forProvider:
    repositoryId: ${oci_devops_repository.test_repository.id}
