apiVersion: fusionapps.oci.upbound.io/v1alpha1
kind: AppsFusionEnvironmentFamily
metadata:
  annotations:
    meta.upbound.io/example-id: fusionapps/v1alpha1/appsfusionenvironmentfamily
  labels:
    testing.upbound.io/example-name: test_fusion_environment_family
  name: test-fusion-environment-family
spec:
  forProvider:
    compartmentId: ${var.compartment_id}
    definedTags:
      foo-namespace.bar-key: value
    displayName: ${var.fusion_environment_family_display_name}
    familyMaintenancePolicy:
    - concurrentMaintenance: ${var.fusion_environment_family_family_maintenance_policy_concurrent_maintenance}
      isMonthlyPatchingEnabled: ${var.fusion_environment_family_family_maintenance_policy_is_monthly_patching_enabled}
      quarterlyUpgradeBeginTimes: ${var.fusion_environment_family_family_maintenance_policy_quarterly_upgrade_begin_times}
    freeformTags:
      bar-key: value
    subscriptionIds: ${var.fusion_environment_family_subscription_ids}
