apiVersion: fusionapps.oci.upbound.io/v1alpha1
kind: AppsFusionEnvironmentAdminUser
metadata:
  annotations:
    meta.upbound.io/example-id: fusionapps/v1alpha1/appsfusionenvironmentadminuser
  labels:
    testing.upbound.io/example-name: test_fusion_environment_admin_user
  name: test-fusion-environment-admin-user
spec:
  forProvider:
    emailAddress: ${var.fusion_environment_admin_user_email_address}
    firstName: ${var.fusion_environment_admin_user_first_name}
    fusionEnvironmentId: ${oci_fusion_apps_fusion_environment.test_fusion_environment.id}
    lastName: ${var.fusion_environment_admin_user_last_name}
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    username: ${var.fusion_environment_admin_user_username}
