apiVersion: fusionapps.oci.upbound.io/v1alpha1
kind: AppsFusionEnvironmentServiceAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: fusionapps/v1alpha1/appsfusionenvironmentserviceattachment
  labels:
    testing.upbound.io/example-name: test_fusion_environment_service_attachment
  name: test-fusion-environment-service-attachment
spec:
  forProvider:
    fusionEnvironmentId: ${oci_fusion_apps_fusion_environment.test_fusion_environment.id}
    serviceInstanceId: ${oci_core_instance.test_instance.id}
    serviceInstanceType: ${var.fusion_environment_service_attachment_service_instance_type}
